package findings

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"rohy/backend/consts"
)

func newStore(t *testing.T) *Store {
	t.Helper()
	s, err := Open(t.TempDir())
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	return s
}

func at(min int) time.Time {
	return time.Date(2026, 7, 14, 10, min, 0, 0, time.UTC)
}

func mustSet(t *testing.T, s *Store, f Finding, now time.Time) *Finding {
	t.Helper()
	got, err := s.Set(f, now)
	if err != nil {
		t.Fatalf("Set(%q): %v", f.Key, err)
	}
	return got
}

func TestSetAndGetRoundTrips(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{
		Key:        "hash-a",
		Flagged:    true,
		Tags:       []string{"lateral-movement"},
		Note:       "pivot host",
		Descriptor: "4624 Security",
	}, at(0))

	got := s.Get("hash-a")
	if got == nil {
		t.Fatal("Get returned nil for a stored finding")
	}
	if !got.Flagged || got.Note != "pivot host" || got.Descriptor != "4624 Security" {
		t.Fatalf("round trip lost content: %+v", got)
	}
	if len(got.Tags) != 1 || got.Tags[0] != "lateral-movement" {
		t.Fatalf("tags = %v", got.Tags)
	}
	if s.Get("hash-missing") != nil {
		t.Error("Get on an unannotated event should return nil")
	}
}

// The sidecar must survive a restart — an analyst's notes are the one thing in the case that
// cannot be regenerated by re-running anything.
func TestFindingsPersistAcrossReopen(t *testing.T) {
	dir := t.TempDir()
	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	mustSet(t, s, Finding{Key: "hash-a", Note: "keep me", Tags: []string{"x"}}, at(0))

	again, err := Open(dir)
	if err != nil {
		t.Fatalf("reopen: %v", err)
	}
	got := again.Get("hash-a")
	if got == nil || got.Note != "keep me" {
		t.Fatalf("finding did not survive reopen: %+v", got)
	}
}

func TestOpenFreshCaseIsEmptyNotAnError(t *testing.T) {
	s := newStore(t)
	if n := len(s.List()); n != 0 {
		t.Fatalf("fresh case has %d findings, want 0", n)
	}
	if s.Stats().Total != 0 {
		t.Error("fresh case reports a non-zero total")
	}
}

// CreatedAt records when a judgement was first made; only UpdatedAt moves on revision.
func TestUpdatePreservesCreatedAt(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Note: "first"}, at(0))
	got := mustSet(t, s, Finding{Key: "hash-a", Note: "revised"}, at(30))

	if !got.CreatedAt.Equal(at(0)) {
		t.Errorf("CreatedAt = %v, want it preserved at %v", got.CreatedAt, at(0))
	}
	if !got.UpdatedAt.Equal(at(30)) {
		t.Errorf("UpdatedAt = %v, want %v", got.UpdatedAt, at(30))
	}
}

// Editing the note must not blank the descriptor captured when the finding was written.
func TestUpdateKeepsDescriptorWhenOmitted(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Note: "n", Descriptor: "4624 Security"}, at(0))
	got := mustSet(t, s, Finding{Key: "hash-a", Note: "edited"}, at(5))
	if got.Descriptor != "4624 Security" {
		t.Errorf("descriptor = %q, want it preserved", got.Descriptor)
	}
}

// Clearing the last piece of content deletes the finding, so the event does not keep
// counting as annotated in filters and stats.
func TestClearingAllContentRemovesTheFinding(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true, Tags: []string{"t"}, Note: "n"}, at(0))

	got := mustSet(t, s, Finding{Key: "hash-a"}, at(5))
	if got != nil {
		t.Fatalf("emptied finding returned %+v, want nil", got)
	}
	if s.Get("hash-a") != nil {
		t.Error("emptied finding is still stored")
	}
	if s.Stats().Total != 0 {
		t.Error("emptied finding still counts in stats")
	}
}

// A whitespace-only note is not content.
func TestWhitespaceOnlyNoteIsNotContent(t *testing.T) {
	s := newStore(t)
	if got := mustSet(t, s, Finding{Key: "hash-a", Note: "   \n\t "}, at(0)); got != nil {
		t.Fatalf("whitespace note stored a finding: %+v", got)
	}
}

func TestSetRequiresAKey(t *testing.T) {
	s := newStore(t)
	if _, err := s.Set(Finding{Key: "  ", Note: "orphan"}, at(0)); err != ErrNoKey {
		t.Fatalf("err = %v, want ErrNoKey", err)
	}
}

// An over-long note is refused, not truncated: silently dropping the tail of an analyst's
// reasoning is worse than saying it did not fit.
func TestOverlongNoteIsRefusedNotTruncated(t *testing.T) {
	s := newStore(t)
	long := strings.Repeat("x", consts.MaxFindingNoteLen+1)
	if _, err := s.Set(Finding{Key: "hash-a", Note: long}, at(0)); err != ErrTooLong {
		t.Fatalf("err = %v, want ErrTooLong", err)
	}
	if s.Get("hash-a") != nil {
		t.Error("refused write still stored a finding")
	}
}

func TestTagsAreNormalizedAndDeduplicated(t *testing.T) {
	s := newStore(t)
	got := mustSet(t, s, Finding{
		Key:  "hash-a",
		Tags: []string{"Lateral Movement", "  lateral movement ", "", "Persistence"},
	}, at(0))

	want := []string{"lateral movement", "persistence"}
	if len(got.Tags) != len(want) {
		t.Fatalf("tags = %v, want %v", got.Tags, want)
	}
	for i, w := range want {
		if got.Tags[i] != w {
			t.Fatalf("tags = %v, want %v", got.Tags, want)
		}
	}
}

func TestTagCountIsCapped(t *testing.T) {
	s := newStore(t)
	many := make([]string, consts.MaxFindingTags+10)
	for i := range many {
		many[i] = string(rune('a'+i%26)) + strings.Repeat("z", i)
	}
	got := mustSet(t, s, Finding{Key: "hash-a", Tags: many}, at(0))
	if len(got.Tags) > consts.MaxFindingTags {
		t.Fatalf("stored %d tags, cap is %d", len(got.Tags), consts.MaxFindingTags)
	}
}

func TestRemoveIsIdempotent(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true}, at(0))
	if err := s.Remove("hash-a"); err != nil {
		t.Fatalf("Remove: %v", err)
	}
	if err := s.Remove("hash-a"); err != nil {
		t.Fatalf("second Remove: %v", err)
	}
	if s.Get("hash-a") != nil {
		t.Error("finding survived removal")
	}
}

func TestListIsMostRecentlyUpdatedFirst(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "old", Flagged: true}, at(0))
	mustSet(t, s, Finding{Key: "new", Flagged: true}, at(30))

	list := s.List()
	if len(list) != 2 || list[0].Key != "new" {
		t.Fatalf("list order = %v", []string{list[0].Key, list[1].Key})
	}
}

func TestGetManySkipsUnannotatedEvents(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true}, at(0))

	got := s.GetMany([]string{"hash-a", "hash-b"})
	if len(got) != 1 || got["hash-a"] == nil {
		t.Fatalf("GetMany = %v, want only hash-a", got)
	}
}

func TestKeysByFilter(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "flagged-only", Flagged: true}, at(0))
	mustSet(t, s, Finding{Key: "noted-only", Note: "why"}, at(1))
	mustSet(t, s, Finding{Key: "tagged-only", Tags: []string{"t"}}, at(2))

	cases := []struct {
		filter string
		want   []string
	}{
		{consts.FindingFilterFlagged, []string{"flagged-only"}},
		{consts.FindingFilterNoted, []string{"noted-only"}},
		{consts.FindingFilterAnnotated, []string{"flagged-only", "noted-only", "tagged-only"}},
	}
	for _, c := range cases {
		got, ok := s.Keys(c.filter)
		if !ok {
			t.Fatalf("%s: ok = false", c.filter)
		}
		if strings.Join(got, ",") != strings.Join(c.want, ",") {
			t.Errorf("%s: keys = %v, want %v", c.filter, got, c.want)
		}
	}
}

// "no findings" is the complement of a key set, not a key set, so the store says so rather
// than returning an empty list the caller would read as "match nothing".
func TestKeysForNoneIsNotExpressibleAsAKeySet(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true}, at(0))
	if _, ok := s.Keys(consts.FindingFilterNone); ok {
		t.Error("Keys(none) reported ok, want false so the caller excludes instead")
	}
}

// A stale UI value must degrade to "annotated" rather than emptying the case.
func TestUnknownFilterDegradesToAnnotated(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true}, at(0))
	got, ok := s.Keys("not-a-real-filter")
	if !ok || len(got) != 1 {
		t.Fatalf("keys = %v ok = %v, want the annotated set", got, ok)
	}
}

func TestTagsAreCountedAndOrderedByUse(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "a", Tags: []string{"common", "rare"}}, at(0))
	mustSet(t, s, Finding{Key: "b", Tags: []string{"common"}}, at(1))

	tags := s.Tags()
	if len(tags) != 2 {
		t.Fatalf("tags = %+v", tags)
	}
	if tags[0].Tag != "common" || tags[0].Count != 2 {
		t.Errorf("first tag = %+v, want common x2", tags[0])
	}
}

func TestKeysWithTagMatchesRegardlessOfCase(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "a", Tags: []string{"Lateral Movement"}}, at(0))
	if got := s.KeysWithTag("  LATERAL MOVEMENT "); len(got) != 1 || got[0] != "a" {
		t.Fatalf("KeysWithTag = %v, want [a]", got)
	}
	if got := s.KeysWithTag(""); len(got) != 0 {
		t.Errorf("empty tag matched %v, want nothing", got)
	}
}

func TestStatsCountsEachKindOfContent(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "a", Flagged: true, Note: "n", Tags: []string{"t"}}, at(0))
	mustSet(t, s, Finding{Key: "b", Flagged: true}, at(1))

	got := s.Stats()
	want := Summary{Total: 2, Flagged: 2, Noted: 1, Tagged: 1}
	if got != want {
		t.Fatalf("stats = %+v, want %+v", got, want)
	}
}

// Callers must not be able to mutate stored state through a returned value.
func TestReturnedFindingsAreCopies(t *testing.T) {
	s := newStore(t)
	mustSet(t, s, Finding{Key: "a", Tags: []string{"original"}}, at(0))

	got := s.Get("a")
	got.Tags[0] = "mutated"
	got.Note = "mutated"

	after := s.Get("a")
	if after.Tags[0] != "original" || after.Note != "" {
		t.Fatalf("store was mutated through a returned value: %+v", after)
	}
}

// The sidecar is meant to be readable without this program.
func TestSidecarIsReadableJSON(t *testing.T) {
	dir := t.TempDir()
	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	mustSet(t, s, Finding{Key: "hash-a", Note: "human readable"}, at(0))

	data, err := os.ReadFile(filepath.Join(dir, findingsFile))
	if err != nil {
		t.Fatalf("read sidecar: %v", err)
	}
	if !strings.Contains(string(data), "human readable") {
		t.Error("note is not legible in the sidecar")
	}
	if !strings.Contains(string(data), "\n  ") {
		t.Error("sidecar is not indented for reading")
	}
}

// The sidecar records which hash_normalized recipe its keys were written against, so a
// future change to that recipe is detectable rather than silently orphaning every finding.
func TestSidecarRecordsTheHashVersion(t *testing.T) {
	dir := t.TempDir()
	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	mustSet(t, s, Finding{Key: "hash-a", Flagged: true}, at(0))

	if s.HashVersion() != consts.FindingsHashVersion {
		t.Errorf("HashVersion = %d, want %d", s.HashVersion(), consts.FindingsHashVersion)
	}
	if s.Stale() {
		t.Error("a sidecar written by this build reports itself stale")
	}
	data, err := os.ReadFile(filepath.Join(dir, findingsFile))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "hash_version") {
		t.Error("sidecar does not record the hash version")
	}
}

// A sidecar from a different recipe still LOADS — the notes are irreplaceable — but reports
// itself stale, because none of its keys can match a live event.
func TestForeignHashVersionLoadsButReportsStale(t *testing.T) {
	dir := t.TempDir()
	doc := `{"hash_version": 99, "findings": {"hash-a": {"key":"hash-a","flagged":true,"note":"keep me"}}}`
	if err := os.WriteFile(filepath.Join(dir, findingsFile), []byte(doc), 0o644); err != nil {
		t.Fatal(err)
	}

	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if !s.Stale() {
		t.Error("a sidecar from another recipe does not report itself stale")
	}
	if s.HashVersion() != 99 {
		t.Errorf("HashVersion = %d, want the stored 99", s.HashVersion())
	}
	if got := s.Get("hash-a"); got == nil || got.Note != "keep me" {
		t.Fatalf("stale sidecar dropped its findings: %+v", got)
	}
}

// A sidecar predating versioning is adopted at the current version rather than treated as
// foreign — version 1 is the only recipe that has ever shipped.
func TestUnversionedSidecarIsAdoptedNotFlagged(t *testing.T) {
	dir := t.TempDir()
	doc := `{"findings": {"hash-a": {"key":"hash-a","flagged":true}}}`
	if err := os.WriteFile(filepath.Join(dir, findingsFile), []byte(doc), 0o644); err != nil {
		t.Fatal(err)
	}

	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if s.Stale() {
		t.Error("an unversioned sidecar was treated as foreign")
	}
	if s.Get("hash-a") == nil {
		t.Error("unversioned sidecar lost its findings")
	}
}

func TestConcurrentUseIsSafe(t *testing.T) {
	s := newStore(t)
	done := make(chan struct{})
	for i := 0; i < 8; i++ {
		go func(i int) {
			defer func() { done <- struct{}{} }()
			key := string(rune('a' + i))
			_, _ = s.Set(Finding{Key: key, Flagged: true, Tags: []string{key}}, at(i))
			_ = s.Get(key)
			_ = s.List()
			_ = s.Tags()
			_ = s.Stats()
			_, _ = s.Keys(consts.FindingFilterFlagged)
		}(i)
	}
	for i := 0; i < 8; i++ {
		<-done
	}
	if s.Stats().Total != 8 {
		t.Fatalf("total = %d, want 8", s.Stats().Total)
	}
}
