// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {annotate} from '../models';

export function Annotations(arg1:number):Promise<api.AnnotationView>;

export function CountOnLayer(arg1:number,arg2:string):Promise<api.LayerDeletion>;

export function DeleteAnnotation(arg1:number,arg2:string):Promise<void>;

export function DeleteLayer(arg1:number,arg2:string):Promise<api.LayerDeletion>;

export function SaveAnnotation(arg1:api.AnnotationRequest):Promise<annotate.Item>;

export function SaveLayer(arg1:api.LayerRequest):Promise<annotate.Layer>;
