// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Annotations(arg1) {
  return window['go']['api']['AnnotateAPI']['Annotations'](arg1);
}

export function CountOnLayer(arg1, arg2) {
  return window['go']['api']['AnnotateAPI']['CountOnLayer'](arg1, arg2);
}

export function DeleteAnnotation(arg1, arg2) {
  return window['go']['api']['AnnotateAPI']['DeleteAnnotation'](arg1, arg2);
}

export function DeleteLayer(arg1, arg2) {
  return window['go']['api']['AnnotateAPI']['DeleteLayer'](arg1, arg2);
}

export function SaveAnnotation(arg1) {
  return window['go']['api']['AnnotateAPI']['SaveAnnotation'](arg1);
}

export function SaveLayer(arg1) {
  return window['go']['api']['AnnotateAPI']['SaveLayer'](arg1);
}
