// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRuleRun() {
  return window['go']['api']['BuildAPI']['CancelRuleRun']();
}

export function DryRunRule(arg1, arg2, arg3) {
  return window['go']['api']['BuildAPI']['DryRunRule'](arg1, arg2, arg3);
}

export function IsRunningRules() {
  return window['go']['api']['BuildAPI']['IsRunningRules']();
}

export function RunRules(arg1) {
  return window['go']['api']['BuildAPI']['RunRules'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['BuildAPI']['Startup'](arg1);
}
