// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {graphbuild} from '../models';
import {context} from '../models';

export function CancelRuleRun():Promise<void>;

export function IsRunningRules():Promise<boolean>;

export function RunRules(arg1:api.BuildRequest):Promise<graphbuild.Result>;

export function Startup(arg1:context.Context):Promise<void>;
