// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelIngestion() {
  return window['go']['api']['EventsAPI']['CancelIngestion']();
}

export function CaptureStatus() {
  return window['go']['api']['EventsAPI']['CaptureStatus']();
}

export function CheckPermissions() {
  return window['go']['api']['EventsAPI']['CheckPermissions']();
}

export function CountEvents(arg1) {
  return window['go']['api']['EventsAPI']['CountEvents'](arg1);
}

export function EvaluateAccess(arg1) {
  return window['go']['api']['EventsAPI']['EvaluateAccess'](arg1);
}

export function GetEvent(arg1) {
  return window['go']['api']['EventsAPI']['GetEvent'](arg1);
}

export function IngestState() {
  return window['go']['api']['EventsAPI']['IngestState']();
}

export function IsIngesting() {
  return window['go']['api']['EventsAPI']['IsIngesting']();
}

export function PauseIngestion() {
  return window['go']['api']['EventsAPI']['PauseIngestion']();
}

export function PickEVTXFiles() {
  return window['go']['api']['EventsAPI']['PickEVTXFiles']();
}

export function PickEVTXFolder() {
  return window['go']['api']['EventsAPI']['PickEVTXFolder']();
}

export function QueryEvents(arg1) {
  return window['go']['api']['EventsAPI']['QueryEvents'](arg1);
}

export function RelaunchAsAdmin() {
  return window['go']['api']['EventsAPI']['RelaunchAsAdmin']();
}

export function ResetCapturePositions(arg1) {
  return window['go']['api']['EventsAPI']['ResetCapturePositions'](arg1);
}

export function ResumeIngestion() {
  return window['go']['api']['EventsAPI']['ResumeIngestion']();
}

export function Shutdown() {
  return window['go']['api']['EventsAPI']['Shutdown']();
}

export function StartIngest(arg1) {
  return window['go']['api']['EventsAPI']['StartIngest'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['EventsAPI']['Startup'](arg1);
}

export function Stats() {
  return window['go']['api']['EventsAPI']['Stats']();
}

export function Timeline(arg1, arg2, arg3) {
  return window['go']['api']['EventsAPI']['Timeline'](arg1, arg2, arg3);
}

export function TotalSize(arg1) {
  return window['go']['api']['EventsAPI']['TotalSize'](arg1);
}
