// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {evtx} from '../models';
import {graphene} from '../models';
import {context} from '../models';

export function CancelIngestion():Promise<void>;

export function CaptureStatus():Promise<api.CaptureStatus>;

export function CheckPermissions():Promise<evtx.PermissionStatus>;

export function CountEvents(arg1:api.EventQuery):Promise<number>;

export function EvaluateAccess(arg1:Array<string>):Promise<evtx.AccessDecision>;

export function GetEvent(arg1:number):Promise<graphene.Event>;

export function IngestState():Promise<string>;

export function IsIngesting():Promise<boolean>;

export function PauseIngestion():Promise<void>;

export function PickEVTXFiles():Promise<Array<string>>;

export function PickEVTXFolder():Promise<Array<string>>;

export function QueryEvents(arg1:api.EventQuery):Promise<Array<graphene.Event>>;

export function RelaunchAsAdmin():Promise<void>;

export function ResetCapturePositions(arg1:string):Promise<void>;

export function ResumeIngestion():Promise<void>;

export function Shutdown():Promise<void>;

export function StartIngest(arg1:api.IngestRequest):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stats():Promise<api.StatsResult>;

export function Timeline(arg1:api.EventQuery,arg2:number,arg3:string):Promise<graphene.TimelineSummary>;

export function TotalSize(arg1:Array<string>):Promise<number>;
