// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuditFindings() {
  return window['go']['api']['FindingsAPI']['AuditFindings']();
}

export function FindingStats() {
  return window['go']['api']['FindingsAPI']['FindingStats']();
}

export function GetFinding(arg1) {
  return window['go']['api']['FindingsAPI']['GetFinding'](arg1);
}

export function GetFindings(arg1) {
  return window['go']['api']['FindingsAPI']['GetFindings'](arg1);
}

export function ListFindings() {
  return window['go']['api']['FindingsAPI']['ListFindings']();
}

export function ListTags() {
  return window['go']['api']['FindingsAPI']['ListTags']();
}

export function RemoveFinding(arg1) {
  return window['go']['api']['FindingsAPI']['RemoveFinding'](arg1);
}

export function SetFinding(arg1) {
  return window['go']['api']['FindingsAPI']['SetFinding'](arg1);
}
