// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {findings} from '../models';

export function AuditFindings():Promise<api.FindingsAudit>;

export function FindingStats():Promise<findings.Summary>;

export function GetFinding(arg1:string):Promise<findings.Finding>;

export function GetFindings(arg1:Array<string>):Promise<Record<string, findings.Finding>>;

export function ListFindings():Promise<Array<findings.Finding>>;

export function ListTags():Promise<Array<findings.TagCount>>;

export function RemoveFinding(arg1:string):Promise<void>;

export function SetFinding(arg1:api.FindingRequest):Promise<findings.Finding>;
