// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveGraph() {
  return window['go']['api']['GraphAPI']['ActiveGraph']();
}

export function CreateGraph(arg1) {
  return window['go']['api']['GraphAPI']['CreateGraph'](arg1);
}

export function CreateRelation(arg1) {
  return window['go']['api']['GraphAPI']['CreateRelation'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['api']['GraphAPI']['DeleteEvent'](arg1);
}

export function DeleteGraph(arg1) {
  return window['go']['api']['GraphAPI']['DeleteGraph'](arg1);
}

export function DeleteRelation(arg1) {
  return window['go']['api']['GraphAPI']['DeleteRelation'](arg1);
}

export function GetEvents(arg1) {
  return window['go']['api']['GraphAPI']['GetEvents'](arg1);
}

export function GetGraphRelations(arg1) {
  return window['go']['api']['GraphAPI']['GetGraphRelations'](arg1);
}

export function GetRelations() {
  return window['go']['api']['GraphAPI']['GetRelations']();
}

export function ListGraphs() {
  return window['go']['api']['GraphAPI']['ListGraphs']();
}

export function LoadLayout(arg1) {
  return window['go']['api']['GraphAPI']['LoadLayout'](arg1);
}

export function RelationsAdjacency(arg1) {
  return window['go']['api']['GraphAPI']['RelationsAdjacency'](arg1);
}

export function RelationsOf(arg1) {
  return window['go']['api']['GraphAPI']['RelationsOf'](arg1);
}

export function RenameGraph(arg1) {
  return window['go']['api']['GraphAPI']['RenameGraph'](arg1);
}

export function SaveLayout(arg1, arg2) {
  return window['go']['api']['GraphAPI']['SaveLayout'](arg1, arg2);
}

export function SetActiveGraph(arg1) {
  return window['go']['api']['GraphAPI']['SetActiveGraph'](arg1);
}

export function UpdateRelation(arg1) {
  return window['go']['api']['GraphAPI']['UpdateRelation'](arg1);
}
