// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {graphreg} from '../models';
import {graphene} from '../models';
import {layout} from '../models';

export function ActiveGraph():Promise<number>;

export function CreateGraph(arg1:api.GraphRequest):Promise<graphreg.Graph>;

export function CreateRelation(arg1:api.RelationRequest):Promise<graphene.Relation>;

export function DeleteEvent(arg1:number):Promise<void>;

export function DeleteGraph(arg1:number):Promise<void>;

export function DeleteRelation(arg1:number):Promise<void>;

export function GetEvents(arg1:Array<number>):Promise<Array<graphene.Event>>;

export function GetGraphRelations(arg1:number):Promise<Array<graphene.Relation>>;

export function GetRelations():Promise<Array<graphene.Relation>>;

export function ListGraphs():Promise<Array<graphreg.Graph>>;

export function LoadLayout(arg1:number):Promise<layout.Layout>;

export function RelationsAdjacency(arg1:Array<number>):Promise<Record<number, graphene.EventAdjacency>>;

export function RelationsOf(arg1:number):Promise<Array<graphene.Relation>>;

export function RenameGraph(arg1:api.GraphRequest):Promise<graphreg.Graph>;

export function SaveLayout(arg1:number,arg2:layout.Layout):Promise<void>;

export function SetActiveGraph(arg1:number):Promise<void>;

export function UpdateRelation(arg1:api.RelationUpdate):Promise<graphene.Relation>;
