// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackfillCorrelationKeys() {
  return window['go']['api']['MaintenanceAPI']['BackfillCorrelationKeys']();
}

export function CancelMaintenance() {
  return window['go']['api']['MaintenanceAPI']['CancelMaintenance']();
}

export function CorrelationKeyStatus() {
  return window['go']['api']['MaintenanceAPI']['CorrelationKeyStatus']();
}

export function IsRunningMaintenance() {
  return window['go']['api']['MaintenanceAPI']['IsRunningMaintenance']();
}

export function Startup(arg1) {
  return window['go']['api']['MaintenanceAPI']['Startup'](arg1);
}
