// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graphene} from '../models';
import {caseintegrity} from '../models';
import {context} from '../models';
import {api} from '../models';

export function BackfillCorrelationKeys():Promise<graphene.BackfillResult>;

export function CancelMaintenance():Promise<void>;

export function CheckIntegrity(arg1:boolean):Promise<caseintegrity.Report>;

export function CorrelationKeyStatus():Promise<graphene.CorrelationKeyStatus>;

export function IsRunningMaintenance():Promise<boolean>;

export function RebuildIndexes():Promise<void>;

export function RepairRelationIndex():Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;

export function WithIntegrity(arg1:api.IntegrityDeps):Promise<api.MaintenanceAPI>;
