// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graphene} from '../models';
import {context} from '../models';

export function BackfillCorrelationKeys():Promise<graphene.BackfillResult>;

export function CancelMaintenance():Promise<void>;

export function CorrelationKeyStatus():Promise<graphene.CorrelationKeyStatus>;

export function IsRunningMaintenance():Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
