// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackfillCorrelationKeys() {
  return window['go']['api']['MaintenanceAPI']['BackfillCorrelationKeys']();
}

export function CancelMaintenance() {
  return window['go']['api']['MaintenanceAPI']['CancelMaintenance']();
}

export function CheckIntegrity(arg1) {
  return window['go']['api']['MaintenanceAPI']['CheckIntegrity'](arg1);
}

export function CorrelationKeyStatus() {
  return window['go']['api']['MaintenanceAPI']['CorrelationKeyStatus']();
}

export function IsRunningMaintenance() {
  return window['go']['api']['MaintenanceAPI']['IsRunningMaintenance']();
}

export function RebuildIndexes() {
  return window['go']['api']['MaintenanceAPI']['RebuildIndexes']();
}

export function RepairRelationIndex() {
  return window['go']['api']['MaintenanceAPI']['RepairRelationIndex']();
}

export function Startup(arg1) {
  return window['go']['api']['MaintenanceAPI']['Startup'](arg1);
}

export function WithIntegrity(arg1) {
  return window['go']['api']['MaintenanceAPI']['WithIntegrity'](arg1);
}
