// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRule(arg1) {
  return window['go']['api']['RulesAPI']['DeleteRule'](arg1);
}

export function ImportRuleFiles() {
  return window['go']['api']['RulesAPI']['ImportRuleFiles']();
}

export function ImportRuleFolder() {
  return window['go']['api']['RulesAPI']['ImportRuleFolder']();
}

export function ListRules() {
  return window['go']['api']['RulesAPI']['ListRules']();
}

export function ReloadRules() {
  return window['go']['api']['RulesAPI']['ReloadRules']();
}

export function RuleSource(arg1) {
  return window['go']['api']['RulesAPI']['RuleSource'](arg1);
}

export function RulesDir() {
  return window['go']['api']['RulesAPI']['RulesDir']();
}

export function SetRuleEnabled(arg1, arg2) {
  return window['go']['api']['RulesAPI']['SetRuleEnabled'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['api']['RulesAPI']['Startup'](arg1);
}
