// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rules} from '../models';
import {api} from '../models';
import {context} from '../models';

export function DeleteRule(arg1:string):Promise<void>;

export function ImportRuleFiles():Promise<rules.ImportResult>;

export function ImportRuleFolder():Promise<rules.ImportResult>;

export function ListRules():Promise<api.RulesResult>;

export function ReloadRules():Promise<api.RulesResult>;

export function RuleSource(arg1:string):Promise<rules.RuleSource>;

export function RulesDir():Promise<string>;

export function SetRuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
