// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRestore(arg1) {
  return window['go']['api']['SnapshotAPI']['ApplyRestore'](arg1);
}

export function DeleteSnapshot(arg1, arg2) {
  return window['go']['api']['SnapshotAPI']['DeleteSnapshot'](arg1, arg2);
}

export function ListSnapshots(arg1) {
  return window['go']['api']['SnapshotAPI']['ListSnapshots'](arg1);
}

export function PreviewRestore(arg1, arg2) {
  return window['go']['api']['SnapshotAPI']['PreviewRestore'](arg1, arg2);
}

export function TakeSnapshot(arg1) {
  return window['go']['api']['SnapshotAPI']['TakeSnapshot'](arg1);
}
