// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {snapshot} from '../models';

export function ApplyRestore(arg1:api.RestoreRequest):Promise<api.RestoreResult>;

export function DeleteSnapshot(arg1:number,arg2:string):Promise<void>;

export function ListSnapshots(arg1:number):Promise<Array<snapshot.Summary>>;

export function PreviewRestore(arg1:number,arg2:string):Promise<snapshot.Plan>;

export function TakeSnapshot(arg1:api.SnapshotRequest):Promise<snapshot.Summary>;
