// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';
import {version} from '../models';

export function Failed(arg1:Error):Promise<void>;

export function InitStatus():Promise<api.InitState>;

export function Ready():Promise<void>;

export function Stage(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Version():Promise<version.Info>;
