// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Failed(arg1) {
  return window['go']['api']['SystemAPI']['Failed'](arg1);
}

export function InitStatus() {
  return window['go']['api']['SystemAPI']['InitStatus']();
}

export function Ready() {
  return window['go']['api']['SystemAPI']['Ready']();
}

export function Stage(arg1) {
  return window['go']['api']['SystemAPI']['Stage'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['SystemAPI']['Startup'](arg1);
}

export function Version() {
  return window['go']['api']['SystemAPI']['Version']();
}
